### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by michi88** [gtnx/pandas-highcharts#14]
```
        open("requirements.txt", "r").readlines()
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "....../build/pandas-highcharts/setup.py", line 14, in <module>

    open("requirements.txt", "r").readlines()

IOError: [Errno 2] No such file or directory: 'requirements.txt'

```

**Comment by gtnx** [comment]
Indeed. I fixed it and deployed another package (version 0.4.0). Could you confirm it's ok now?

**Comment by michi88** [comment]
Yes, awesome!! You are fast! :+1:
