### ISSUE TITLE
failing to import display_charts from python (v2.7.10), working fine with %load from IPython

### ISSUE THREAD

**Issue by ManieqZ** [gtnx/pandas-highcharts#32]
1. Thank you very much for your work. Combination of pandas with highcharts makes the graphic creation on the webpage a very entertaining exercise. 

Nevertheless under OSX I have notices a problem when importing the display_charts. 
Everything appears to work as expected when using the IPython (v4.1.2). When trying to use the examples from pure python (v2.7.10) I see the following error: 

```
# > python  app2.py

Traceback (most recent call last):
  File "app2.py", line 11, in <module>
    from pandas_highcharts.display import display_charts
  File "build/bdist.macosx-10.11-x86_64/egg/pandas_highcharts/display.py", line 32, in <module>
AttributeError: 'NoneType' object has no attribute 'config'
```

The _app2.py_ code presents itself as: 

```
from flask import Flask, render_template
import pandas as pd
from pandas_highcharts.core import serialize
import ConfigParser
import os

from pandas_highcharts.display import display_charts
[..]
```

Am I missing something ?

Thank you in advance for your comments / support. 

Cheers,
ManieqZ

**Comment by shezankazi** [comment]
I get the same error... any news on this?

**Comment by cici** [comment]
Still no solution?
